
# http://localhost/askomics/
# http://localhost/virtuoso

version: '2'
services:
    askomics:
        image: local_askomics
        command: ./startAskomics.sh -r -t virtuoso -d prod
        environment:
            TRIPLESTORE_ENDPOINT: "http://virtuoso:8890/sparql"
            ASKOMICS_LOAD_URL: "http://askomics:6543"
            ASKOMICS_SMTP_HOST: postfix
            ASKOMICS_SMTP_PORT: 25
            ASKOMICS_SMTP_LOGIN: admin
            ASKOMICS_SMTP_PASSWORD: passasko
            TRIPLESTORE_ENDPOINT_USERNAME : dba
            TRIPLESTORE_ENDPOINT_PASSWD : dba
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    virtuoso:
        image: askomics/virtuoso
        environment:
            VIRT_Parameters_NumberOfBuffers: 10000   # See virtuoso/README.md to adapt value of this line
            VIRT_Parameters_MaxDirtyBuffers: 6000    # See virtuoso/README.md to adapt value of this line
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 30000
            VIRT_SPARQL_MaxQueryExecutionTime: 30000
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        volumes:
            - ./output-container/virtuoso:/data
    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics #=> http://localhost:80/askomics
            TPS_REL_URL: virtuoso      #=> http://localhost:80/virtuoso
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
