
# http://localhost/askomics/
# http://localhost/virtuoso

version: '2'
services:
    askomics:
        image: askomics/askomics
        image : test
        command: ./startAskomics.sh -t rdf4j -d prod
        environment:
            ASKO_endpoint: "http://rdf4j:8080/rdf4j-server/repositories/SYSTEM"
            ASKO_updatepoint: "http://rdf4j:8080/rdf4j-server/repositories/SYSTEM/statements"
            ASKO_load_url: "http://askomics:6543"
            ASKO_smtp_host: postfix
            ASKO_smtp_port: 25
            ASKO_smtp_login: admin
            ASKO_smtp_password: passasko
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    blazegraph:
        image: lyrasis/blazegraph:2.1.4
        volumes:
            - ./output-container/blazegraph:/var/lib/jetty
    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics #=> http://localhost:80/askomics
            TPS_REL_URL: blazegraph      #=> http://localhost:80/blazegraph
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    postfix:
        image: catatnight/postfix
        environment:
            maildomain: mail.askomics.org
            smtp_user: admin:passasko
