
# http://localhost/askomics/
# http://localhost/virtuoso

version: '2'
services:
    askomics:
        image: askomics/docker-askomics
        command: ./startAskomics.sh -r -t virtuoso -d prod
        environment:
            ASKO_endpoint: "http://virtuoso:8890/sparql"
            ASKO_load_url: "http://askomics:6543"
            ASKO_smtp_host: postfix
            ASKO_smtp_port: 25
            ASKO_smtp_login: admin
            ASKO_smtp_password: passasko
            ASKO_enpoint_username : dba
            ASKO_endpoint_passwd : dba
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    virtuoso:
        image: tenforce/virtuoso
        environment:
            VIRT_Parameters_NumberOfBuffers: 680000
            VIRT_Parameters_MaxDirtyBuffers: 500000
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 30000
            VIRT_SPARQL_MaxQueryExecutionTime: 30000
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        volumes:
            - ./output-container/virtuoso:/data
    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics #=> http://localhost:80/askomics
            TPS_REL_URL: virtuoso      #=> http://localhost:80/virtuoso
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    postfix:
        image: catatnight/postfix
        environment:
            maildomain: mail.askomics.org
            smtp_user: admin:passasko
