version: '3'
services:
    askomics:
        image: askomics/askomics
        command: ./startAskomics.sh -r -d prod
        environment:
            ASKO_endpoint: "http://virtuoso:8890/sparql"
            ASKO_load_url: "http://askomics:6543"
            ASKO_triplestore_results_max_rows: 100000000 # same as VIRT_SPARQL_ResultSetMaxRows in virtuoso image
            ASKO_endpoint_username : dba
            ASKO_endpoint_passwd : dba
        volumes:
            - ./output/askomics:/tmp/askomics

    virtuoso:
        image: askomics/virtuoso
        environment:
            VIRT_Parameters_NumberOfBuffers: 10000   # See virtuoso/README.md to adapt value of this line
            VIRT_Parameters_MaxDirtyBuffers: 6000    # See virtuoso/README.md to adapt value of this line
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000000 # same as ASKO_triplestore_results_max_rows in askomics image
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            VIRT_StopCompilerWhenXOverRunTime: 1
            VIRT_MaxQueryCostEstimationTime: 400000
            VIRT_MaxQueryExecutionTime: 60000000
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        volumes:
            - ./output/virtuoso:/data

    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/tmp/nginx.conf
            - ./output/nginx/log:/var/log/nginx
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_URL: askomics
            TPS_URL: virtuoso
        command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
