version: '3'
services:
    askomics:
        image: askomics/askomics
        command: ./startAskomics.sh -r -d prod
        environment:
            ASKO_endpoint: http://fuseki:3030/askomics/query
            ASKO_updatepoint: http://fuseki:3030/askomics/update
            ASKO_endpoint_username: admin
            ASKO_endpoint_passwd: admin # Same as ADMIN_PASSWORD in fuseki image
            ASKO_load_url: http://askomics:6543
            ASKO_hack_virtuoso: "false"
        volumes:
            - ./output/askomics:/tmp/askomics

    fuseki:
        image: xgaia/jena-fuseki:dev
        environment:
            ADMIN_PASSWORD: admin
            JVM_ARGS: -Xmx2g # See fuseki/README.md to adapt value of this line
            FUSEKI_DATASET_1: askomics
        volumes:
            - ./output/fuseki:/fuseki

    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/tmp/nginx.conf
            - ./output/nginx/log:/var/log/nginx
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_URL: askomics
            TPS_URL: fuseki
        command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
