
# http://localhost/askomics/
# http://localhost/virtuoso

version: '2'
services:
    askomics:
        image: askomics/docker-askomics
        command: ./startAskomics.sh -t fuseki -d prod
        links:
            - fuseki
        environment:
            ASKO_endpoint: "http://fuseki:3030/database/query"
            ASKO_updatepoint: "http://fuseki:3030/database/update"
            ASKO_load_url: "http://askomics:6543"
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    fuseki:
        image: askomics/jena-fuseki
        build: ./fuseki
        environment:
            ADMIN_PASSWORD: "pw123"
            JVM_ARGS: "-Xmx2g"
        volumes:
            - ./output-container/fuseki/databases:/databases

    nginx:
        image: nginx
        links:
            - askomics
            - fuseki
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics #=> http://localhost:80/askomics
            TPS_REL_URL: fuseki      #=> http://localhost:80/virtuoso
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
