version: '2'
services:
  askomics:
    image: askomics/askomics:test
    command:
    - virtuoso
    - prod
    ports:
    - "6543:6543"
    volumes:
    - ./askomics:/usr/local/askomics
    - ./tmp/askomics:/tmp
    - logvolume01:/var/log
    links:
    - virtuoso
  virtuoso:
    image: tenforce/virtuoso
    ports:
    - "8890:8890"
    - "1111:1111"
    environment:
    - VIRT_Parameters_TN_MAX_memory=4000000000
    - VIRT_SPARQL_ResultSetMaxRows=100000
    - VIRT_SPARQL_MaxQueryCostEstimationTime=300
    - VIRT_SPARQL_MaxQueryExecutionTime=300
    - VIRT_SPARQL_MaxDataSourceSize=1000000000
    - VIRT_Flags_TN_MAX_memory=4000000000
    - DBA_PASSWORD=dba
    - SPARQL_UPDATE=true
    - DEFAULT_GRAPH=http://localhost:8890/DAV
    volumes:
    - ./data/virtuoso:/data
  ld-vowl:
    image: ofilangi/docker-ld-vowl
  nginx:
    image: nginx
    volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  logvolume01: {}

