version: '2'
services:
    askomics:
        image: askomics/askomics
        ports:
            - "6542:6543"
        links:
            - virtuoso
        environment:
            TRIPLESTORE_ENDPOINT: "http://virtuoso:8890/sparql"
            ASKOMICS_LOAD_URL: "http://askomics:6543"
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    virtuoso:
        image: tenforce/virtuoso
        environment:
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 300
            VIRT_SPARQL_MaxQueryExecutionTime: 300
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        ports:
            - "8891:8890"
            - "1111:1111"
        volumes:
            - ./output-container/virtuoso:/data

    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "8080:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
        
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

