version: '3'
services:
    askomics:
        image: askomics/askomics
        links:
            - virtuoso
        environment:
            ASKO_endpoint: "http://virtuoso:8890/sparql"
            ASKO_load_url: "http://askomics:6543"
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    virtuoso:
        image: askomics/virtuoso
        environment:
            VIRT_Parameters_NumberOfBuffers: 510000
            VIRT_Parameters_MaxDirtyBuffers: 375000
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 300
            VIRT_SPARQL_MaxQueryExecutionTime: 300
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        volumes:
            - ./output-container/virtuoso:/data

    galaxy:
        image: galaxy-askomics
        links:
            - askomics
        environment:
            NONUSE: proftp,reports
            GALAXY_CONFIG_CONDA_COPY_DEPENDENCIES: "True"
            GALAXY_LOGGING: full
            GALAXY_CONFIG_BRAND: "AskOmics"
            GALAXY_CONFIG_CONDA_AUTO_INIT: "True"
            GALAXY_CONFIG_CONDA_AUTO_INSTALL: "True"
            ASKOMICS_URL: "http://askomics"
            ASKOMICS_PORT: "6543"
        volumes:
            - ./galaxy.ini:/etc/galaxy/galaxy.ini
            - ./output-container/galaxy:/export

    nginx:
        image: nginx
        links:
            - askomics
            - virtuoso
            - galaxy
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/default.conf
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics
            TPS_REL_URL: virtuoso
            GALAXY_REL_URL: galaxy
