
# http://localhost/askomics/
# http://localhost/virtuoso

version: '2'
services:
    askomics:
        image: askomics/askomics:federation
        command: ./startAskomics.sh -r -t virtuoso -d prod
        environment:
            ASKO_endpoint: "http://virtuoso:8890/sparql"
            ASKO_fdendpoint: "http://fedx4askomics:4040/fedx"
            ASKO_load_url: "http://askomics:6543"
            ASKO_hack_virtuoso : "true"
            ASKO_allowed_file_types : "'application/octet-stream','text/turtle','text/plain','text/csv','text/tab-separated-values','text/fasta'"
            ASKO_smtp_host: postfix
            ASKO_smtp_port: 25
            ASKO_smtp_login: admin
            ASKO_smtp_password: passasko
            ASKO_endpoint_username : dba
            ASKO_endpoint_passwd : dba
        volumes:
            - ./output-container/askomics/ttl/askomics:/tmp

    virtuoso:
        image: askomics/virtuoso
        environment:
            VIRT_Parameters_NumberOfBuffers: 510000
            VIRT_Parameters_MaxDirtyBuffers: 375000
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000000
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
            VIRT_StopCompilerWhenXOverRunTime: 1
            VIRT_MaxQueryCostEstimationTime: 0       # query time estimation
            VIRT_MaxQueryExecutionTime: 600          # 10 min
            DBA_PASSWORD: "dba"
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://localhost:8890/DAV"
        volumes:
            - ./output-container/virtuoso:/data
    fedx4askomics:
        image: askomics/fedx4askomics:rdf4j
    nginx:
        image: nginx
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
            - ./output-container/nginx/log:/var/log/nginx/
        ports:
            - "80:80"
        environment:
            NGINX_HOST: localhost
            NGINX_PORT: 80
            ASKOMICS_REL_URL: askomics #=> http://localhost:80/askomics
            TPS_REL_URL: virtuoso      #=> http://localhost:80/virtuoso
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    postfix:
        image: catatnight/postfix
        environment:
            maildomain: mail.askomics.org
            smtp_user: admin:passasko

    rdfsurveyor:
        image: askomics/rdfsurveyor
